language: python

addons:
  postgresql: '9.6'

services:
- postgresql
- redis-server
- docker

python:
- '3.6'

dist: xenial
sudo: required

node_js:
- '10'

cache:
  pip: true
  yarn: true
  directories:
  - node_modules

install:
- pip install -U pip setuptools
- pip install -r py/tests/requirements.txt
- pip install -r py/requirements.txt
- cp py/setup.cfg .
- node -v
- npm -v
- yarn -v
- cd js && yarn && cd ..

script:
- make lint
- REAL_STRIPE_TESTS=1 make test && bash <(curl -s https://codecov.io/bash)
- make testjs
#- bash <(curl -s https://codecov.io/bash)
- make build
- ls -lha
