language: python

addons:
  postgresql: '9.6'

services:
- postgresql
- redis-server
- docker

python:
- '3.6'

cache:
  pip: true

install:
- pip install -U pip setuptools
- pip install -r py/tests/requirements.txt
- pip install -r py/requirements.txt
- cp py/setup.cfg .

script:
- make lint
# send to codecov if make test passes regardless of other fails, also without waiting for build
- REAL_STRIPE_TESTS=1 make test
- make testjs
- bash <(curl -s https://codecov.io/bash)
- make build
- ls -lha
