# ===============================================
# js build stage
FROM alpine:3.7 as js-build
RUN apk --no-cache add yarn
WORKDIR /home/root

ADD ./js/package.json /home/root/package.json
ADD ./js/yarn.lock /home/root/yarn.lock
RUN yarn

ADD ./js/.env /home/root/.env
ADD ./deploy-settings/*.* /home/root/
ADD ./js/src /home/root/src
ADD ./js/public /home/root/public
ADD ./deploy-settings/favicons/* /home/root/public/
RUN yarn build
RUN rm build/service-worker.js
RUN find build/ -type f

# ===============================================
# pre-built python build stage
FROM nosht-python-build as python-build

# ===============================================
# final image
FROM python:3.6-alpine3.7
COPY --from=python-build /usr/local/lib/python3.6/site-packages /usr/local/lib/python3.6/site-packages
COPY --from=python-build /lib/* /lib/
COPY --from=python-build /usr/lib/* /usr/lib/

ENV PYTHONUNBUFFERED 1
ENV APP_ON_DOCKER 1
WORKDIR /home/root/py
RUN adduser -D runuser
USER runuser

ADD ./py/run.py /home/root/py/run.py
ADD ./py/shared /home/root/py/shared
ADD ./py/web /home/root/py/web
COPY --from=js-build /home/root/build /home/root/js/build

CMD ["./run.py", "web"]
