version: '3.4'

volumes:
 pg_data: {}
 redis_data: {}

services:
  logs:
    image: gliderlabs/logspout
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    ports:
    - 5001:80

  postgres:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
    # to connect: `pgcli postgre://postgres:docker@localhost:54320/nosht`
    - 54320:5432
    volumes:
    - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    depends_on:
    - logs

  redis:
    image: redis:4-alpine
    volumes:
    - redis_data:/data
    restart: unless-stopped
    depends_on:
    - logs

  web:
    image: nosht-web
    environment:
      DATABASE_URL: 'postgres://postgres:docker@postgres:5432/nosht'
      REDISCLOUD_URL: 'redis://redis:6379'
      PORT: 8000
      APP_AWS_ACCESS_KEY: '${APP_AWS_ACCESS_KEY}'
      APP_AWS_SECRET_KEY: '${APP_AWS_SECRET_KEY}'
      APP_S3_BUCKET: '${APP_S3_BUCKET}'
      APP_S3_DOMAIN: '${APP_S3_DOMAIN}'
      APP_S3_PREFIX: docker
      APP_GRECAPTCHA_SECRET: '${APP_GRECAPTCHA_SECRET}'
      APP_STRIPE_IDEMPOTENCY_EXTRA: docker
    restart: unless-stopped
    ports:
    - 8000:8000
    depends_on:
    - postgres
    - redis

  worker:
    image: nosht-worker
    environment:
      DATABASE_URL: 'postgres://postgres:docker@postgres:5432/nosht'
      REDISCLOUD_URL: 'redis://redis:6379'
      APP_AWS_ACCESS_KEY: '${APP_AWS_ACCESS_KEY}'
      APP_AWS_SECRET_KEY: '${APP_AWS_SECRET_KEY}'
      APP_S3_BUCKET: '${APP_S3_BUCKET}'
      APP_S3_DOMAIN: '${APP_S3_DOMAIN}'
      APP_S3_PREFIX: docker
      APP_GRECAPTCHA_SECRET: '${APP_GRECAPTCHA_SECRET}'
      APP_STRIPE_IDEMPOTENCY_EXTRA: docker
    restart: unless-stopped
    depends_on:
    - postgres
    - redis
