export default [
  {value: 'Pacific/Midway', display_name: 'Pacific Midway (-11)'},
  {value: 'Pacific/Niue', display_name: 'Pacific Niue (-11)'},
  {value: 'Pacific/Pago_Pago', display_name: 'Pacific Pago Pago (-11)'},
  {value: 'Pacific/Samoa', display_name: 'Pacific Samoa (-11)'},
  {value: 'US/Samoa', display_name: 'US Samoa (-11)'},
  {value: 'Pacific/Honolulu', display_name: 'Pacific Honolulu (-10)'},
  {value: 'Pacific/Johnston', display_name: 'Pacific Johnston (-10)'},
  {value: 'Pacific/Rarotonga', display_name: 'Pacific Rarotonga (-10)'},
  {value: 'Pacific/Tahiti', display_name: 'Pacific Tahiti (-10)'},
  {value: 'US/Hawaii', display_name: 'US Hawaii (-10)'},
  {value: 'America/Adak', display_name: 'America Adak (-10 or -9)'},
  {value: 'America/Atka', display_name: 'America Atka (-10 or -9)'},
  {value: 'Pacific/Marquesas', display_name: 'Pacific Marquesas (-10)'},
  {value: 'US/Aleutian', display_name: 'US Aleutian (-10 or -9)'},
  {value: 'Pacific/Gambier', display_name: 'Pacific Gambier (-9)'},
  {value: 'America/Anchorage', display_name: 'America Anchorage (-9 or -8)'},
  {value: 'America/Juneau', display_name: 'America Juneau (-9 or -8)'},
  {value: 'America/Metlakatla', display_name: 'America Metlakatla (-9 or -8)'},
  {value: 'America/Nome', display_name: 'America Nome (-9 or -8)'},
  {value: 'America/Sitka', display_name: 'America Sitka (-9 or -8)'},
  {value: 'America/Yakutat', display_name: 'America Yakutat (-9 or -8)'},
  {value: 'US/Alaska', display_name: 'US Alaska (-9 or -8)'},
  {value: 'Pacific/Pitcairn', display_name: 'Pacific Pitcairn (-8)'},
  {value: 'America/Dawson', display_name: 'America Dawson (-8 or -7)'},
  {value: 'America/Ensenada', display_name: 'America Ensenada (-8 or -7)'},
  {value: 'America/Los_Angeles', display_name: 'America Los Angeles (-8 or -7)'},
  {value: 'America/Santa_Isabel', display_name: 'America Santa Isabel (-8 or -7)'},
  {value: 'America/Tijuana', display_name: 'America Tijuana (-8 or -7)'},
  {value: 'America/Vancouver', display_name: 'America Vancouver (-8 or -7)'},
  {value: 'America/Whitehorse', display_name: 'America Whitehorse (-8 or -7)'},
  {value: 'Canada/Pacific', display_name: 'Canada Pacific (-8 or -7)'},
  {value: 'Canada/Yukon', display_name: 'Canada Yukon (-8 or -7)'},
  {value: 'Mexico/BajaNorte', display_name: 'Mexico BajaNorte (-8 or -7)'},
  {value: 'US/Pacific', display_name: 'US Pacific (-8 or -7)'},
  {value: 'America/Creston', display_name: 'America Creston (-7)'},
  {value: 'America/Dawson_Creek', display_name: 'America Dawson Creek (-7)'},
  {value: 'America/Fort_Nelson', display_name: 'America Fort Nelson (-7)'},
  {value: 'America/Hermosillo', display_name: 'America Hermosillo (-7)'},
  {value: 'America/Phoenix', display_name: 'America Phoenix (-7)'},
  {value: 'MST', display_name: 'MST (-7)'},
  {value: 'US/Arizona', display_name: 'US Arizona (-7)'},
  {value: 'America/Boise', display_name: 'America Boise (-7 or -6)'},
  {value: 'America/Cambridge_Bay', display_name: 'America Cambridge Bay (-7 or -6)'},
  {value: 'America/Chihuahua', display_name: 'America Chihuahua (-7 or -6)'},
  {value: 'America/Denver', display_name: 'America Denver (-7 or -6)'},
  {value: 'America/Edmonton', display_name: 'America Edmonton (-7 or -6)'},
  {value: 'America/Inuvik', display_name: 'America Inuvik (-7 or -6)'},
  {value: 'America/Mazatlan', display_name: 'America Mazatlan (-7 or -6)'},
  {value: 'America/Ojinaga', display_name: 'America Ojinaga (-7 or -6)'},
  {value: 'America/Shiprock', display_name: 'America Shiprock (-7 or -6)'},
  {value: 'America/Yellowknife', display_name: 'America Yellowknife (-7 or -6)'},
  {value: 'Canada/Mountain', display_name: 'Canada Mountain (-7 or -6)'},
  {value: 'Mexico/BajaSur', display_name: 'Mexico BajaSur (-7 or -6)'},
  {value: 'Navajo', display_name: 'Navajo (-7 or -6)'},
  {value: 'US/Mountain', display_name: 'US Mountain (-7 or -6)'},
  {value: 'America/Belize', display_name: 'America Belize (-6)'},
  {value: 'America/Costa_Rica', display_name: 'America Costa Rica (-6)'},
  {value: 'America/El_Salvador', display_name: 'America El Salvador (-6)'},
  {value: 'America/Guatemala', display_name: 'America Guatemala (-6)'},
  {value: 'America/Managua', display_name: 'America Managua (-6)'},
  {value: 'America/Regina', display_name: 'America Regina (-6)'},
  {value: 'America/Swift_Current', display_name: 'America Swift Current (-6)'},
  {value: 'America/Tegucigalpa', display_name: 'America Tegucigalpa (-6)'},
  {value: 'Canada/Saskatchewan', display_name: 'Canada Saskatchewan (-6)'},
  {value: 'Pacific/Galapagos', display_name: 'Pacific Galapagos (-6)'},
  {value: 'America/Bahia_Banderas', display_name: 'America Bahia Banderas (-6 or -5)'},
  {value: 'America/Chicago', display_name: 'America Chicago (-6 or -5)'},
  {value: 'America/Indiana/Knox', display_name: 'America Indiana Knox (-6 or -5)'},
  {value: 'America/Indiana/Tell_City', display_name: 'America Indiana Tell City (-6 or -5)'},
  {value: 'America/Knox_IN', display_name: 'America Knox IN (-6 or -5)'},
  {value: 'America/Matamoros', display_name: 'America Matamoros (-6 or -5)'},
  {value: 'America/Menominee', display_name: 'America Menominee (-6 or -5)'},
  {value: 'America/Merida', display_name: 'America Merida (-6 or -5)'},
  {value: 'America/Mexico_City', display_name: 'America Mexico City (-6 or -5)'},
  {value: 'America/Monterrey', display_name: 'America Monterrey (-6 or -5)'},
  {value: 'America/North_Dakota/Beulah', display_name: 'America North Dakota Beulah (-6 or -5)'},
  {value: 'America/North_Dakota/Center', display_name: 'America North Dakota Center (-6 or -5)'},
  {value: 'America/North_Dakota/New_Salem', display_name: 'America North Dakota New Salem (-6 or -5)'},
  {value: 'America/Rainy_River', display_name: 'America Rainy River (-6 or -5)'},
  {value: 'America/Rankin_Inlet', display_name: 'America Rankin Inlet (-6 or -5)'},
  {value: 'America/Resolute', display_name: 'America Resolute (-6 or -5)'},
  {value: 'America/Winnipeg', display_name: 'America Winnipeg (-6 or -5)'},
  {value: 'Canada/Central', display_name: 'Canada Central (-6 or -5)'},
  {value: 'Chile/EasterIsland', display_name: 'Chile EasterIsland (-5 or -6)'},
  {value: 'Mexico/General', display_name: 'Mexico General (-6 or -5)'},
  {value: 'Pacific/Easter', display_name: 'Pacific Easter (-5 or -6)'},
  {value: 'US/Central', display_name: 'US Central (-6 or -5)'},
  {value: 'US/Indiana-Starke', display_name: 'US Indiana-Starke (-6 or -5)'},
  {value: 'America/Atikokan', display_name: 'America Atikokan (-5)'},
  {value: 'America/Bogota', display_name: 'America Bogota (-5)'},
  {value: 'America/Cancun', display_name: 'America Cancun (-5)'},
  {value: 'America/Cayman', display_name: 'America Cayman (-5)'},
  {value: 'America/Coral_Harbour', display_name: 'America Coral Harbour (-5)'},
  {value: 'America/Eirunepe', display_name: 'America Eirunepe (-5)'},
  {value: 'America/Guayaquil', display_name: 'America Guayaquil (-5)'},
  {value: 'America/Jamaica', display_name: 'America Jamaica (-5)'},
  {value: 'America/Lima', display_name: 'America Lima (-5)'},
  {value: 'America/Panama', display_name: 'America Panama (-5)'},
  {value: 'America/Porto_Acre', display_name: 'America Porto Acre (-5)'},
  {value: 'America/Rio_Branco', display_name: 'America Rio Branco (-5)'},
  {value: 'Brazil/Acre', display_name: 'Brazil Acre (-5)'},
  {value: 'EST', display_name: 'EST (-5)'},
  {value: 'Jamaica', display_name: 'Jamaica (-5)'},
  {value: 'America/Detroit', display_name: 'America Detroit (-5 or -4)'},
  {value: 'America/Fort_Wayne', display_name: 'America Fort Wayne (-5 or -4)'},
  {value: 'America/Havana', display_name: 'America Havana (-5 or -4)'},
  {value: 'America/Indiana/Indianapolis', display_name: 'America Indiana Indianapolis (-5 or -4)'},
  {value: 'America/Indiana/Marengo', display_name: 'America Indiana Marengo (-5 or -4)'},
  {value: 'America/Indiana/Petersburg', display_name: 'America Indiana Petersburg (-5 or -4)'},
  {value: 'America/Indiana/Vevay', display_name: 'America Indiana Vevay (-5 or -4)'},
  {value: 'America/Indiana/Vincennes', display_name: 'America Indiana Vincennes (-5 or -4)'},
  {value: 'America/Indiana/Winamac', display_name: 'America Indiana Winamac (-5 or -4)'},
  {value: 'America/Indianapolis', display_name: 'America Indianapolis (-5 or -4)'},
  {value: 'America/Iqaluit', display_name: 'America Iqaluit (-5 or -4)'},
  {value: 'America/Kentucky/Louisville', display_name: 'America Kentucky Louisville (-5 or -4)'},
  {value: 'America/Kentucky/Monticello', display_name: 'America Kentucky Monticello (-5 or -4)'},
  {value: 'America/Louisville', display_name: 'America Louisville (-5 or -4)'},
  {value: 'America/Montreal', display_name: 'America Montreal (-5 or -4)'},
  {value: 'America/Nassau', display_name: 'America Nassau (-5 or -4)'},
  {value: 'America/New_York', display_name: 'America New York (-5 or -4)'},
  {value: 'America/Nipigon', display_name: 'America Nipigon (-5 or -4)'},
  {value: 'America/Pangnirtung', display_name: 'America Pangnirtung (-5 or -4)'},
  {value: 'America/Port-au-Prince', display_name: 'America Port-au-Prince (-5 or -4)'},
  {value: 'America/Thunder_Bay', display_name: 'America Thunder Bay (-5 or -4)'},
  {value: 'America/Toronto', display_name: 'America Toronto (-5 or -4)'},
  {value: 'Canada/Eastern', display_name: 'Canada Eastern (-5 or -4)'},
  {value: 'Cuba', display_name: 'Cuba (-5 or -4)'},
  {value: 'US/East-Indiana', display_name: 'US East-Indiana (-5 or -4)'},
  {value: 'US/Eastern', display_name: 'US Eastern (-5 or -4)'},
  {value: 'US/Michigan', display_name: 'US Michigan (-5 or -4)'},
  {value: 'America/Anguilla', display_name: 'America Anguilla (-4)'},
  {value: 'America/Antigua', display_name: 'America Antigua (-4)'},
  {value: 'America/Aruba', display_name: 'America Aruba (-4)'},
  {value: 'America/Barbados', display_name: 'America Barbados (-4)'},
  {value: 'America/Blanc-Sablon', display_name: 'America Blanc-Sablon (-4)'},
  {value: 'America/Boa_Vista', display_name: 'America Boa Vista (-4)'},
  {value: 'America/Caracas', display_name: 'America Caracas (-4)'},
  {value: 'America/Curacao', display_name: 'America Curacao (-4)'},
  {value: 'America/Dominica', display_name: 'America Dominica (-4)'},
  {value: 'America/Grand_Turk', display_name: 'America Grand Turk (-4)'},
  {value: 'America/Grenada', display_name: 'America Grenada (-4)'},
  {value: 'America/Guadeloupe', display_name: 'America Guadeloupe (-4)'},
  {value: 'America/Guyana', display_name: 'America Guyana (-4)'},
  {value: 'America/Kralendijk', display_name: 'America Kralendijk (-4)'},
  {value: 'America/La_Paz', display_name: 'America La Paz (-4)'},
  {value: 'America/Lower_Princes', display_name: 'America Lower Princes (-4)'},
  {value: 'America/Manaus', display_name: 'America Manaus (-4)'},
  {value: 'America/Marigot', display_name: 'America Marigot (-4)'},
  {value: 'America/Martinique', display_name: 'America Martinique (-4)'},
  {value: 'America/Montserrat', display_name: 'America Montserrat (-4)'},
  {value: 'America/Port_of_Spain', display_name: 'America Port of Spain (-4)'},
  {value: 'America/Porto_Velho', display_name: 'America Porto Velho (-4)'},
  {value: 'America/Puerto_Rico', display_name: 'America Puerto Rico (-4)'},
  {value: 'America/Santo_Domingo', display_name: 'America Santo Domingo (-4)'},
  {value: 'America/St_Barthelemy', display_name: 'America St Barthelemy (-4)'},
  {value: 'America/St_Kitts', display_name: 'America St Kitts (-4)'},
  {value: 'America/St_Lucia', display_name: 'America St Lucia (-4)'},
  {value: 'America/St_Thomas', display_name: 'America St Thomas (-4)'},
  {value: 'America/St_Vincent', display_name: 'America St Vincent (-4)'},
  {value: 'America/Tortola', display_name: 'America Tortola (-4)'},
  {value: 'America/Virgin', display_name: 'America Virgin (-4)'},
  {value: 'Brazil/West', display_name: 'Brazil West (-4)'},
  {value: 'America/Asuncion', display_name: 'America Asuncion (-3 or -4)'},
  {value: 'America/Campo_Grande', display_name: 'America Campo Grande (-3 or -4)'},
  {value: 'America/Cuiaba', display_name: 'America Cuiaba (-3 or -4)'},
  {value: 'America/Glace_Bay', display_name: 'America Glace Bay (-4 or -3)'},
  {value: 'America/Goose_Bay', display_name: 'America Goose Bay (-4 or -3)'},
  {value: 'America/Halifax', display_name: 'America Halifax (-4 or -3)'},
  {value: 'America/Moncton', display_name: 'America Moncton (-4 or -3)'},
  {value: 'America/Santiago', display_name: 'America Santiago (-3 or -4)'},
  {value: 'America/Thule', display_name: 'America Thule (-4 or -3)'},
  {value: 'Atlantic/Bermuda', display_name: 'Atlantic Bermuda (-4 or -3)'},
  {value: 'Canada/Atlantic', display_name: 'Canada Atlantic (-4 or -3)'},
  {value: 'Chile/Continental', display_name: 'Chile Continental (-3 or -4)'},
  {value: 'America/Araguaina', display_name: 'America Araguaina (-3)'},
  {value: 'America/Argentina/Buenos_Aires', display_name: 'America Argentina Buenos Aires (-3)'},
  {value: 'America/Argentina/Catamarca', display_name: 'America Argentina Catamarca (-3)'},
  {value: 'America/Argentina/ComodRivadavia', display_name: 'America Argentina ComodRivadavia (-3)'},
  {value: 'America/Argentina/Cordoba', display_name: 'America Argentina Cordoba (-3)'},
  {value: 'America/Argentina/Jujuy', display_name: 'America Argentina Jujuy (-3)'},
  {value: 'America/Argentina/La_Rioja', display_name: 'America Argentina La Rioja (-3)'},
  {value: 'America/Argentina/Mendoza', display_name: 'America Argentina Mendoza (-3)'},
  {value: 'America/Argentina/Rio_Gallegos', display_name: 'America Argentina Rio Gallegos (-3)'},
  {value: 'America/Argentina/Salta', display_name: 'America Argentina Salta (-3)'},
  {value: 'America/Argentina/San_Juan', display_name: 'America Argentina San Juan (-3)'},
  {value: 'America/Argentina/San_Luis', display_name: 'America Argentina San Luis (-3)'},
  {value: 'America/Argentina/Tucuman', display_name: 'America Argentina Tucuman (-3)'},
  {value: 'America/Argentina/Ushuaia', display_name: 'America Argentina Ushuaia (-3)'},
  {value: 'America/Bahia', display_name: 'America Bahia (-3)'},
  {value: 'America/Belem', display_name: 'America Belem (-3)'},
  {value: 'America/Buenos_Aires', display_name: 'America Buenos Aires (-3)'},
  {value: 'America/Catamarca', display_name: 'America Catamarca (-3)'},
  {value: 'America/Cayenne', display_name: 'America Cayenne (-3)'},
  {value: 'America/Cordoba', display_name: 'America Cordoba (-3)'},
  {value: 'America/Fortaleza', display_name: 'America Fortaleza (-3)'},
  {value: 'America/Jujuy', display_name: 'America Jujuy (-3)'},
  {value: 'America/Maceio', display_name: 'America Maceio (-3)'},
  {value: 'America/Mendoza', display_name: 'America Mendoza (-3)'},
  {value: 'America/Montevideo', display_name: 'America Montevideo (-3)'},
  {value: 'America/Paramaribo', display_name: 'America Paramaribo (-3)'},
  {value: 'America/Punta_Arenas', display_name: 'America Punta Arenas (-3)'},
  {value: 'America/Recife', display_name: 'America Recife (-3)'},
  {value: 'America/Rosario', display_name: 'America Rosario (-3)'},
  {value: 'America/Santarem', display_name: 'America Santarem (-3)'},
  {value: 'America/St_Johns', display_name: 'America St Johns (-4 or -2)'},
  {value: 'Antarctica/Palmer', display_name: 'Antarctica Palmer (-3)'},
  {value: 'Antarctica/Rothera', display_name: 'Antarctica Rothera (-3)'},
  {value: 'Atlantic/Stanley', display_name: 'Atlantic Stanley (-3)'},
  {value: 'Canada/Newfoundland', display_name: 'Canada Newfoundland (-4 or -2)'},
  {value: 'America/Godthab', display_name: 'America Godthab (-3 or -2)'},
  {value: 'America/Miquelon', display_name: 'America Miquelon (-3 or -2)'},
  {value: 'America/Sao_Paulo', display_name: 'America Sao Paulo (-2 or -3)'},
  {value: 'Brazil/East', display_name: 'Brazil East (-2 or -3)'},
  {value: 'America/Noronha', display_name: 'America Noronha (-2)'},
  {value: 'Atlantic/South_Georgia', display_name: 'Atlantic South Georgia (-2)'},
  {value: 'Brazil/DeNoronha', display_name: 'Brazil DeNoronha (-2)'},
  {value: 'Atlantic/Cape_Verde', display_name: 'Atlantic Cape Verde (-1)'},
  {value: 'America/Scoresbysund', display_name: 'America Scoresbysund (-1 or +0)'},
  {value: 'Atlantic/Azores', display_name: 'Atlantic Azores (-1 or +0)'},
  {value: 'Africa/Abidjan', display_name: 'Africa Abidjan (+0)'},
  {value: 'Africa/Accra', display_name: 'Africa Accra (+0)'},
  {value: 'Africa/Bamako', display_name: 'Africa Bamako (+0)'},
  {value: 'Africa/Banjul', display_name: 'Africa Banjul (+0)'},
  {value: 'Africa/Bissau', display_name: 'Africa Bissau (+0)'},
  {value: 'Africa/Casablanca', display_name: 'Africa Casablanca (+0)'},
  {value: 'Africa/Conakry', display_name: 'Africa Conakry (+0)'},
  {value: 'Africa/Dakar', display_name: 'Africa Dakar (+0)'},
  {value: 'Africa/El_Aaiun', display_name: 'Africa El Aaiun (+0)'},
  {value: 'Africa/Freetown', display_name: 'Africa Freetown (+0)'},
  {value: 'Africa/Lome', display_name: 'Africa Lome (+0)'},
  {value: 'Africa/Monrovia', display_name: 'Africa Monrovia (+0)'},
  {value: 'Africa/Nouakchott', display_name: 'Africa Nouakchott (+0)'},
  {value: 'Africa/Ouagadougou', display_name: 'Africa Ouagadougou (+0)'},
  {value: 'Africa/Timbuktu', display_name: 'Africa Timbuktu (+0)'},
  {value: 'America/Danmarkshavn', display_name: 'America Danmarkshavn (+0)'},
  {value: 'Atlantic/Reykjavik', display_name: 'Atlantic Reykjavik (+0)'},
  {value: 'Atlantic/St_Helena', display_name: 'Atlantic St Helena (+0)'},
  {value: 'Iceland', display_name: 'Iceland (+0)'},
  {value: 'UTC', display_name: 'UTC/GMT (+0)'},
  {value: 'Africa/Sao_Tome', display_name: 'Africa Sao Tome (+0 or +1)'},
  {value: 'Atlantic/Canary', display_name: 'Atlantic Canary (+0 or +1)'},
  {value: 'Atlantic/Faeroe', display_name: 'Atlantic Faeroe (+0 or +1)'},
  {value: 'Atlantic/Faroe', display_name: 'Atlantic Faroe (+0 or +1)'},
  {value: 'Atlantic/Madeira', display_name: 'Atlantic Madeira (+0 or +1)'},
  {value: 'Europe/Belfast', display_name: 'Europe Belfast (+0 or +1)'},
  {value: 'Europe/Dublin', display_name: 'Europe Dublin (+0 or +1)'},
  {value: 'Europe/Guernsey', display_name: 'Europe Guernsey (+0 or +1)'},
  {value: 'Europe/Isle_of_Man', display_name: 'Europe Isle of Man (+0 or +1)'},
  {value: 'Europe/Jersey', display_name: 'Europe Jersey (+0 or +1)'},
  {value: 'Europe/Lisbon', display_name: 'Europe Lisbon (+0 or +1)'},
  {value: 'Europe/London', display_name: 'Europe London (+0 or +1)'},
  {value: 'Portugal', display_name: 'Portugal (+0 or +1)'},
  {value: 'WET', display_name: 'WET (+0 or +1)'},
  {value: 'Africa/Algiers', display_name: 'Africa Algiers (+1)'},
  {value: 'Africa/Bangui', display_name: 'Africa Bangui (+1)'},
  {value: 'Africa/Brazzaville', display_name: 'Africa Brazzaville (+1)'},
  {value: 'Africa/Douala', display_name: 'Africa Douala (+1)'},
  {value: 'Africa/Kinshasa', display_name: 'Africa Kinshasa (+1)'},
  {value: 'Africa/Lagos', display_name: 'Africa Lagos (+1)'},
  {value: 'Africa/Libreville', display_name: 'Africa Libreville (+1)'},
  {value: 'Africa/Luanda', display_name: 'Africa Luanda (+1)'},
  {value: 'Africa/Malabo', display_name: 'Africa Malabo (+1)'},
  {value: 'Africa/Ndjamena', display_name: 'Africa Ndjamena (+1)'},
  {value: 'Africa/Niamey', display_name: 'Africa Niamey (+1)'},
  {value: 'Africa/Porto-Novo', display_name: 'Africa Porto-Novo (+1)'},
  {value: 'Africa/Tunis', display_name: 'Africa Tunis (+1)'},
  {value: 'Antarctica/Troll', display_name: 'Antarctica Troll (+0 or +2)'},
  {value: 'Africa/Ceuta', display_name: 'Africa Ceuta (+1 or +2)'},
  {value: 'Arctic/Longyearbyen', display_name: 'Arctic Longyearbyen (+1 or +2)'},
  {value: 'Atlantic/Jan_Mayen', display_name: 'Atlantic Jan Mayen (+1 or +2)'},
  {value: 'CET', display_name: 'CET (+1 or +2)'},
  {value: 'Europe/Amsterdam', display_name: 'Europe Amsterdam (+1 or +2)'},
  {value: 'Europe/Andorra', display_name: 'Europe Andorra (+1 or +2)'},
  {value: 'Europe/Belgrade', display_name: 'Europe Belgrade (+1 or +2)'},
  {value: 'Europe/Berlin', display_name: 'Europe Berlin (+1 or +2)'},
  {value: 'Europe/Bratislava', display_name: 'Europe Bratislava (+1 or +2)'},
  {value: 'Europe/Brussels', display_name: 'Europe Brussels (+1 or +2)'},
  {value: 'Europe/Budapest', display_name: 'Europe Budapest (+1 or +2)'},
  {value: 'Europe/Busingen', display_name: 'Europe Busingen (+1 or +2)'},
  {value: 'Europe/Copenhagen', display_name: 'Europe Copenhagen (+1 or +2)'},
  {value: 'Europe/Gibraltar', display_name: 'Europe Gibraltar (+1 or +2)'},
  {value: 'Europe/Ljubljana', display_name: 'Europe Ljubljana (+1 or +2)'},
  {value: 'Europe/Luxembourg', display_name: 'Europe Luxembourg (+1 or +2)'},
  {value: 'Europe/Madrid', display_name: 'Europe Madrid (+1 or +2)'},
  {value: 'Europe/Malta', display_name: 'Europe Malta (+1 or +2)'},
  {value: 'Europe/Monaco', display_name: 'Europe Monaco (+1 or +2)'},
  {value: 'Europe/Oslo', display_name: 'Europe Oslo (+1 or +2)'},
  {value: 'Europe/Paris', display_name: 'Europe Paris (+1 or +2)'},
  {value: 'Europe/Podgorica', display_name: 'Europe Podgorica (+1 or +2)'},
  {value: 'Europe/Prague', display_name: 'Europe Prague (+1 or +2)'},
  {value: 'Europe/Rome', display_name: 'Europe Rome (+1 or +2)'},
  {value: 'Europe/San_Marino', display_name: 'Europe San Marino (+1 or +2)'},
  {value: 'Europe/Sarajevo', display_name: 'Europe Sarajevo (+1 or +2)'},
  {value: 'Europe/Skopje', display_name: 'Europe Skopje (+1 or +2)'},
  {value: 'Europe/Stockholm', display_name: 'Europe Stockholm (+1 or +2)'},
  {value: 'Europe/Tirane', display_name: 'Europe Tirane (+1 or +2)'},
  {value: 'Europe/Vaduz', display_name: 'Europe Vaduz (+1 or +2)'},
  {value: 'Europe/Vatican', display_name: 'Europe Vatican (+1 or +2)'},
  {value: 'Europe/Vienna', display_name: 'Europe Vienna (+1 or +2)'},
  {value: 'Europe/Warsaw', display_name: 'Europe Warsaw (+1 or +2)'},
  {value: 'Europe/Zagreb', display_name: 'Europe Zagreb (+1 or +2)'},
  {value: 'Europe/Zurich', display_name: 'Europe Zurich (+1 or +2)'},
  {value: 'MET', display_name: 'MET (+1 or +2)'},
  {value: 'Poland', display_name: 'Poland (+1 or +2)'},
  {value: 'Africa/Blantyre', display_name: 'Africa Blantyre (+2)'},
  {value: 'Africa/Bujumbura', display_name: 'Africa Bujumbura (+2)'},
  {value: 'Africa/Cairo', display_name: 'Africa Cairo (+2)'},
  {value: 'Africa/Gaborone', display_name: 'Africa Gaborone (+2)'},
  {value: 'Africa/Harare', display_name: 'Africa Harare (+2)'},
  {value: 'Africa/Johannesburg', display_name: 'Africa Johannesburg (+2)'},
  {value: 'Africa/Khartoum', display_name: 'Africa Khartoum (+2)'},
  {value: 'Africa/Kigali', display_name: 'Africa Kigali (+2)'},
  {value: 'Africa/Lubumbashi', display_name: 'Africa Lubumbashi (+2)'},
  {value: 'Africa/Lusaka', display_name: 'Africa Lusaka (+2)'},
  {value: 'Africa/Maputo', display_name: 'Africa Maputo (+2)'},
  {value: 'Africa/Maseru', display_name: 'Africa Maseru (+2)'},
  {value: 'Africa/Mbabane', display_name: 'Africa Mbabane (+2)'},
  {value: 'Africa/Tripoli', display_name: 'Africa Tripoli (+2)'},
  {value: 'Africa/Windhoek', display_name: 'Africa Windhoek (+2)'},
  {value: 'Egypt', display_name: 'Egypt (+2)'},
  {value: 'Europe/Kaliningrad', display_name: 'Europe Kaliningrad (+2)'},
  {value: 'Libya', display_name: 'Libya (+2)'},
  {value: 'Asia/Amman', display_name: 'Asia Amman (+2 or +3)'},
  {value: 'Asia/Beirut', display_name: 'Asia Beirut (+2 or +3)'},
  {value: 'Asia/Damascus', display_name: 'Asia Damascus (+2 or +3)'},
  {value: 'Asia/Famagusta', display_name: 'Asia Famagusta (+2 or +3)'},
  {value: 'Asia/Gaza', display_name: 'Asia Gaza (+2 or +3)'},
  {value: 'Asia/Hebron', display_name: 'Asia Hebron (+2 or +3)'},
  {value: 'Asia/Jerusalem', display_name: 'Asia Jerusalem (+2 or +3)'},
  {value: 'Asia/Nicosia', display_name: 'Asia Nicosia (+2 or +3)'},
  {value: 'Asia/Tel_Aviv', display_name: 'Asia Tel Aviv (+2 or +3)'},
  {value: 'EET', display_name: 'EET (+2 or +3)'},
  {value: 'Europe/Athens', display_name: 'Europe Athens (+2 or +3)'},
  {value: 'Europe/Bucharest', display_name: 'Europe Bucharest (+2 or +3)'},
  {value: 'Europe/Chisinau', display_name: 'Europe Chisinau (+2 or +3)'},
  {value: 'Europe/Helsinki', display_name: 'Europe Helsinki (+2 or +3)'},
  {value: 'Europe/Kiev', display_name: 'Europe Kiev (+2 or +3)'},
  {value: 'Europe/Mariehamn', display_name: 'Europe Mariehamn (+2 or +3)'},
  {value: 'Europe/Nicosia', display_name: 'Europe Nicosia (+2 or +3)'},
  {value: 'Europe/Riga', display_name: 'Europe Riga (+2 or +3)'},
  {value: 'Europe/Sofia', display_name: 'Europe Sofia (+2 or +3)'},
  {value: 'Europe/Tallinn', display_name: 'Europe Tallinn (+2 or +3)'},
  {value: 'Europe/Tiraspol', display_name: 'Europe Tiraspol (+2 or +3)'},
  {value: 'Europe/Uzhgorod', display_name: 'Europe Uzhgorod (+2 or +3)'},
  {value: 'Europe/Vilnius', display_name: 'Europe Vilnius (+2 or +3)'},
  {value: 'Europe/Zaporozhye', display_name: 'Europe Zaporozhye (+2 or +3)'},
  {value: 'Israel', display_name: 'Israel (+2 or +3)'},
  {value: 'Africa/Addis_Ababa', display_name: 'Africa Addis Ababa (+3)'},
  {value: 'Africa/Asmara', display_name: 'Africa Asmara (+3)'},
  {value: 'Africa/Asmera', display_name: 'Africa Asmera (+3)'},
  {value: 'Africa/Dar_es_Salaam', display_name: 'Africa Dar es Salaam (+3)'},
  {value: 'Africa/Djibouti', display_name: 'Africa Djibouti (+3)'},
  {value: 'Africa/Juba', display_name: 'Africa Juba (+3)'},
  {value: 'Africa/Kampala', display_name: 'Africa Kampala (+3)'},
  {value: 'Africa/Mogadishu', display_name: 'Africa Mogadishu (+3)'},
  {value: 'Africa/Nairobi', display_name: 'Africa Nairobi (+3)'},
  {value: 'Antarctica/Syowa', display_name: 'Antarctica Syowa (+3)'},
  {value: 'Asia/Aden', display_name: 'Asia Aden (+3)'},
  {value: 'Asia/Baghdad', display_name: 'Asia Baghdad (+3)'},
  {value: 'Asia/Bahrain', display_name: 'Asia Bahrain (+3)'},
  {value: 'Asia/Istanbul', display_name: 'Asia Istanbul (+3)'},
  {value: 'Asia/Kuwait', display_name: 'Asia Kuwait (+3)'},
  {value: 'Asia/Qatar', display_name: 'Asia Qatar (+3)'},
  {value: 'Asia/Riyadh', display_name: 'Asia Riyadh (+3)'},
  {value: 'Europe/Istanbul', display_name: 'Europe Istanbul (+3)'},
  {value: 'Europe/Kirov', display_name: 'Europe Kirov (+3)'},
  {value: 'Europe/Minsk', display_name: 'Europe Minsk (+3)'},
  {value: 'Europe/Moscow', display_name: 'Europe Moscow (+3)'},
  {value: 'Europe/Simferopol', display_name: 'Europe Simferopol (+3)'},
  {value: 'Europe/Volgograd', display_name: 'Europe Volgograd (+3)'},
  {value: 'Indian/Antananarivo', display_name: 'Indian Antananarivo (+3)'},
  {value: 'Indian/Comoro', display_name: 'Indian Comoro (+3)'},
  {value: 'Indian/Mayotte', display_name: 'Indian Mayotte (+3)'},
  {value: 'Turkey', display_name: 'Turkey (+3)'},
  {value: 'W-SU', display_name: 'W-SU (+3)'},
  {value: 'Asia/Baku', display_name: 'Asia Baku (+4)'},
  {value: 'Asia/Dubai', display_name: 'Asia Dubai (+4)'},
  {value: 'Asia/Muscat', display_name: 'Asia Muscat (+4)'},
  {value: 'Asia/Tbilisi', display_name: 'Asia Tbilisi (+4)'},
  {value: 'Asia/Tehran', display_name: 'Asia Tehran (+4 or +4)'},
  {value: 'Asia/Yerevan', display_name: 'Asia Yerevan (+4)'},
  {value: 'Europe/Astrakhan', display_name: 'Europe Astrakhan (+4)'},
  {value: 'Europe/Samara', display_name: 'Europe Samara (+4)'},
  {value: 'Europe/Saratov', display_name: 'Europe Saratov (+4)'},
  {value: 'Europe/Ulyanovsk', display_name: 'Europe Ulyanovsk (+4)'},
  {value: 'Indian/Mahe', display_name: 'Indian Mahe (+4)'},
  {value: 'Indian/Mauritius', display_name: 'Indian Mauritius (+4)'},
  {value: 'Indian/Reunion', display_name: 'Indian Reunion (+4)'},
  {value: 'Iran', display_name: 'Iran (+4 or +4)'},
  {value: 'Asia/Kabul', display_name: 'Asia Kabul (+4)'},
  {value: 'Antarctica/Mawson', display_name: 'Antarctica Mawson (+5)'},
  {value: 'Asia/Aqtau', display_name: 'Asia Aqtau (+5)'},
  {value: 'Asia/Aqtobe', display_name: 'Asia Aqtobe (+5)'},
  {value: 'Asia/Ashgabat', display_name: 'Asia Ashgabat (+5)'},
  {value: 'Asia/Ashkhabad', display_name: 'Asia Ashkhabad (+5)'},
  {value: 'Asia/Atyrau', display_name: 'Asia Atyrau (+5)'},
  {value: 'Asia/Dushanbe', display_name: 'Asia Dushanbe (+5)'},
  {value: 'Asia/Karachi', display_name: 'Asia Karachi (+5)'},
  {value: 'Asia/Oral', display_name: 'Asia Oral (+5)'},
  {value: 'Asia/Samarkand', display_name: 'Asia Samarkand (+5)'},
  {value: 'Asia/Tashkent', display_name: 'Asia Tashkent (+5)'},
  {value: 'Asia/Yekaterinburg', display_name: 'Asia Yekaterinburg (+5)'},
  {value: 'Indian/Kerguelen', display_name: 'Indian Kerguelen (+5)'},
  {value: 'Indian/Maldives', display_name: 'Indian Maldives (+5)'},
  {value: 'Asia/Calcutta', display_name: 'Asia Calcutta (+6)'},
  {value: 'Asia/Colombo', display_name: 'Asia Colombo (+6)'},
  {value: 'Asia/Kolkata', display_name: 'Asia Kolkata (+6)'},
  {value: 'Asia/Kathmandu', display_name: 'Asia Kathmandu (+6)'},
  {value: 'Asia/Katmandu', display_name: 'Asia Katmandu (+6)'},
  {value: 'Antarctica/Vostok', display_name: 'Antarctica Vostok (+6)'},
  {value: 'Asia/Almaty', display_name: 'Asia Almaty (+6)'},
  {value: 'Asia/Bishkek', display_name: 'Asia Bishkek (+6)'},
  {value: 'Asia/Dacca', display_name: 'Asia Dacca (+6)'},
  {value: 'Asia/Dhaka', display_name: 'Asia Dhaka (+6)'},
  {value: 'Asia/Kashgar', display_name: 'Asia Kashgar (+6)'},
  {value: 'Asia/Omsk', display_name: 'Asia Omsk (+6)'},
  {value: 'Asia/Qyzylorda', display_name: 'Asia Qyzylorda (+6)'},
  {value: 'Asia/Thimbu', display_name: 'Asia Thimbu (+6)'},
  {value: 'Asia/Thimphu', display_name: 'Asia Thimphu (+6)'},
  {value: 'Asia/Urumqi', display_name: 'Asia Urumqi (+6)'},
  {value: 'Indian/Chagos', display_name: 'Indian Chagos (+6)'},
  {value: 'Asia/Rangoon', display_name: 'Asia Rangoon (+6)'},
  {value: 'Asia/Yangon', display_name: 'Asia Yangon (+6)'},
  {value: 'Indian/Cocos', display_name: 'Indian Cocos (+6)'},
  {value: 'Antarctica/Davis', display_name: 'Antarctica Davis (+7)'},
  {value: 'Asia/Bangkok', display_name: 'Asia Bangkok (+7)'},
  {value: 'Asia/Barnaul', display_name: 'Asia Barnaul (+7)'},
  {value: 'Asia/Ho_Chi_Minh', display_name: 'Asia Ho Chi Minh (+7)'},
  {value: 'Asia/Hovd', display_name: 'Asia Hovd (+7)'},
  {value: 'Asia/Jakarta', display_name: 'Asia Jakarta (+7)'},
  {value: 'Asia/Krasnoyarsk', display_name: 'Asia Krasnoyarsk (+7)'},
  {value: 'Asia/Novokuznetsk', display_name: 'Asia Novokuznetsk (+7)'},
  {value: 'Asia/Novosibirsk', display_name: 'Asia Novosibirsk (+7)'},
  {value: 'Asia/Phnom_Penh', display_name: 'Asia Phnom Penh (+7)'},
  {value: 'Asia/Pontianak', display_name: 'Asia Pontianak (+7)'},
  {value: 'Asia/Saigon', display_name: 'Asia Saigon (+7)'},
  {value: 'Asia/Tomsk', display_name: 'Asia Tomsk (+7)'},
  {value: 'Asia/Vientiane', display_name: 'Asia Vientiane (+7)'},
  {value: 'Indian/Christmas', display_name: 'Indian Christmas (+7)'},
  {value: 'Asia/Brunei', display_name: 'Asia Brunei (+8)'},
  {value: 'Asia/Choibalsan', display_name: 'Asia Choibalsan (+8)'},
  {value: 'Asia/Chongqing', display_name: 'Asia Chongqing (+8)'},
  {value: 'Asia/Chungking', display_name: 'Asia Chungking (+8)'},
  {value: 'Asia/Harbin', display_name: 'Asia Harbin (+8)'},
  {value: 'Asia/Hong_Kong', display_name: 'Asia Hong Kong (+8)'},
  {value: 'Asia/Irkutsk', display_name: 'Asia Irkutsk (+8)'},
  {value: 'Asia/Kuala_Lumpur', display_name: 'Asia Kuala Lumpur (+8)'},
  {value: 'Asia/Kuching', display_name: 'Asia Kuching (+8)'},
  {value: 'Asia/Macao', display_name: 'Asia Macao (+8)'},
  {value: 'Asia/Macau', display_name: 'Asia Macau (+8)'},
  {value: 'Asia/Makassar', display_name: 'Asia Makassar (+8)'},
  {value: 'Asia/Manila', display_name: 'Asia Manila (+8)'},
  {value: 'Asia/Shanghai', display_name: 'Asia Shanghai (+8)'},
  {value: 'Asia/Singapore', display_name: 'Asia Singapore (+8)'},
  {value: 'Asia/Taipei', display_name: 'Asia Taipei (+8)'},
  {value: 'Asia/Ujung_Pandang', display_name: 'Asia Ujung Pandang (+8)'},
  {value: 'Asia/Ulaanbaatar', display_name: 'Asia Ulaanbaatar (+8)'},
  {value: 'Asia/Ulan_Bator', display_name: 'Asia Ulan Bator (+8)'},
  {value: 'Australia/Perth', display_name: 'Australia Perth (+8)'},
  {value: 'Australia/West', display_name: 'Australia West (+8)'},
  {value: 'ROC', display_name: 'ROC (+8)'},
  {value: 'Asia/Pyongyang', display_name: 'Asia Pyongyang (+8 or +9)'},
  {value: 'Australia/Eucla', display_name: 'Australia Eucla (+9)'},
  {value: 'Asia/Chita', display_name: 'Asia Chita (+9)'},
  {value: 'Asia/Dili', display_name: 'Asia Dili (+9)'},
  {value: 'Asia/Jayapura', display_name: 'Asia Jayapura (+9)'},
  {value: 'Asia/Khandyga', display_name: 'Asia Khandyga (+9)'},
  {value: 'Asia/Seoul', display_name: 'Asia Seoul (+9)'},
  {value: 'Asia/Tokyo', display_name: 'Asia Tokyo (+9)'},
  {value: 'Asia/Yakutsk', display_name: 'Asia Yakutsk (+9)'},
  {value: 'Japan', display_name: 'Japan (+9)'},
  {value: 'Pacific/Palau', display_name: 'Pacific Palau (+9)'},
  {value: 'ROK', display_name: 'ROK (+9)'},
  {value: 'Antarctica/Casey', display_name: 'Antarctica Casey (+11 or +8)'},
  {value: 'Australia/Darwin', display_name: 'Australia Darwin (+10)'},
  {value: 'Australia/North', display_name: 'Australia North (+10)'},
  {value: 'Antarctica/DumontDUrville', display_name: 'Antarctica DumontDUrville (+10)'},
  {value: 'Asia/Ust-Nera', display_name: 'Asia Ust-Nera (+10)'},
  {value: 'Asia/Vladivostok', display_name: 'Asia Vladivostok (+10)'},
  {value: 'Australia/Adelaide', display_name: 'Australia Adelaide (+10 or +10)'},
  {value: 'Australia/Brisbane', display_name: 'Australia Brisbane (+10)'},
  {value: 'Australia/Broken_Hill', display_name: 'Australia Broken Hill (+10 or +10)'},
  {value: 'Australia/Lindeman', display_name: 'Australia Lindeman (+10)'},
  {value: 'Australia/Queensland', display_name: 'Australia Queensland (+10)'},
  {value: 'Australia/South', display_name: 'Australia South (+10 or +10)'},
  {value: 'Australia/Yancowinna', display_name: 'Australia Yancowinna (+10 or +10)'},
  {value: 'Pacific/Chuuk', display_name: 'Pacific Chuuk (+10)'},
  {value: 'Pacific/Guam', display_name: 'Pacific Guam (+10)'},
  {value: 'Pacific/Port_Moresby', display_name: 'Pacific Port Moresby (+10)'},
  {value: 'Pacific/Saipan', display_name: 'Pacific Saipan (+10)'},
  {value: 'Pacific/Truk', display_name: 'Pacific Truk (+10)'},
  {value: 'Pacific/Yap', display_name: 'Pacific Yap (+10)'},
  {value: 'Australia/ACT', display_name: 'Australia ACT (+11 or +10)'},
  {value: 'Australia/Canberra', display_name: 'Australia Canberra (+11 or +10)'},
  {value: 'Australia/Currie', display_name: 'Australia Currie (+11 or +10)'},
  {value: 'Australia/Hobart', display_name: 'Australia Hobart (+11 or +10)'},
  {value: 'Australia/Melbourne', display_name: 'Australia Melbourne (+11 or +10)'},
  {value: 'Australia/NSW', display_name: 'Australia NSW (+11 or +10)'},
  {value: 'Australia/Sydney', display_name: 'Australia Sydney (+11 or +10)'},
  {value: 'Australia/Tasmania', display_name: 'Australia Tasmania (+11 or +10)'},
  {value: 'Australia/Victoria', display_name: 'Australia Victoria (+11 or +10)'},
  {value: 'Australia/LHI', display_name: 'Australia LHI (+11 or +10)'},
  {value: 'Australia/Lord_Howe', display_name: 'Australia Lord Howe (+11 or +10)'},
  {value: 'Antarctica/Macquarie', display_name: 'Antarctica Macquarie (+11)'},
  {value: 'Asia/Magadan', display_name: 'Asia Magadan (+11)'},
  {value: 'Asia/Sakhalin', display_name: 'Asia Sakhalin (+11)'},
  {value: 'Asia/Srednekolymsk', display_name: 'Asia Srednekolymsk (+11)'},
  {value: 'Pacific/Bougainville', display_name: 'Pacific Bougainville (+11)'},
  {value: 'Pacific/Efate', display_name: 'Pacific Efate (+11)'},
  {value: 'Pacific/Guadalcanal', display_name: 'Pacific Guadalcanal (+11)'},
  {value: 'Pacific/Kosrae', display_name: 'Pacific Kosrae (+11)'},
  {value: 'Pacific/Norfolk', display_name: 'Pacific Norfolk (+11)'},
  {value: 'Pacific/Noumea', display_name: 'Pacific Noumea (+11)'},
  {value: 'Pacific/Pohnpei', display_name: 'Pacific Pohnpei (+11)'},
  {value: 'Pacific/Ponape', display_name: 'Pacific Ponape (+11)'},
  {value: 'Asia/Anadyr', display_name: 'Asia Anadyr (+12)'},
  {value: 'Asia/Kamchatka', display_name: 'Asia Kamchatka (+12)'},
  {value: 'Kwajalein', display_name: 'Kwajalein (+12)'},
  {value: 'Pacific/Funafuti', display_name: 'Pacific Funafuti (+12)'},
  {value: 'Pacific/Kwajalein', display_name: 'Pacific Kwajalein (+12)'},
  {value: 'Pacific/Majuro', display_name: 'Pacific Majuro (+12)'},
  {value: 'Pacific/Nauru', display_name: 'Pacific Nauru (+12)'},
  {value: 'Pacific/Tarawa', display_name: 'Pacific Tarawa (+12)'},
  {value: 'Pacific/Wake', display_name: 'Pacific Wake (+12)'},
  {value: 'Pacific/Wallis', display_name: 'Pacific Wallis (+12)'},
  {value: 'Antarctica/McMurdo', display_name: 'Antarctica McMurdo (+13 or +12)'},
  {value: 'Antarctica/South_Pole', display_name: 'Antarctica South Pole (+13 or +12)'},
  {value: 'NZ', display_name: 'NZ (+13 or +12)'},
  {value: 'Pacific/Auckland', display_name: 'Pacific Auckland (+13 or +12)'},
  {value: 'Pacific/Fiji', display_name: 'Pacific Fiji (+13 or +12)'},
  {value: 'Pacific/Enderbury', display_name: 'Pacific Enderbury (+13)'},
  {value: 'Pacific/Fakaofo', display_name: 'Pacific Fakaofo (+13)'},
  {value: 'Pacific/Tongatapu', display_name: 'Pacific Tongatapu (+13)'},
  {value: 'Pacific/Chatham', display_name: 'Pacific Chatham (+14 or +13)'},
  {value: 'Pacific/Apia', display_name: 'Pacific Apia (+14 or +13)'},
  {value: 'Pacific/Kiritimati', display_name: 'Pacific Kiritimati (+14)'},
]
